

apiVersion: v1
kind: Pod
metadata:
  name: kubectluser
  namespace: sa04
spec:
  serviceAccountName: scboss
  containers:
    - image: bitnami/kubectl
      name: kubectluser
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      ports:
      - containerPort: 80
  restartPolicy: Never